# Generated by Django 5.0.4 on 2024-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brandName',
            field=models.CharField(choices=[('Prima', 'Prima'), ('Cleantex', 'Cleantex'), (' Parex', 'Parex'), ('Ariane', 'Ariane')], max_length=50),
        ),
    ]
