# Generated by Django 5.0.4 on 2024-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brandName',
            field=models.CharField(choices=[('Prima', 'Prima'), ('Cleantex', 'Cleantex'), ('Parex', 'Parex'), ('Ariane', 'Ariane')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
