# Generated by Django 5.0.4 on 2024-04-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_brandname_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brandName',
            new_name='brand',
        ),
    ]
