# Generated by Django 5.0.4 on 2024-04-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_brandname_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Prima', 'prima'), ('Cleantex', 'cleantex'), ('Parex', 'parex'), ('Ariane', 'ariane')], max_length=50),
        ),
    ]
