# Generated by Django 5.0.4 on 2024-04-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='totalReviewCount',
            field=models.IntegerField(default=0),
        ),
    ]
